### ISSUE TITLE
Installation fails on macOS

### ISSUE THREAD

**Issue by rafmudaf** [fonsocarre/UVLM#4]
With the Intel compiler (I set CPP = icc in `src/Makefile`), I get this error:

```
(sharpy_env) >>mbp@~/Desktop/UVLM (develop *)$ ./run_make.sh 
mkdir -p lib
make -C src/
make[1]: Entering directory '/Users/rmudafor/Desktop/UVLM/src'
icc -fPIC -O3 -std=c++14 -march=x86-64 -mtune=generic -DEIGEN_USE_MKL_ALL -I/Users/rmudafor/miniconda3/envs/sharpy_env/include -I/Users/rmudafor/miniconda3/envs/sharpy_env/include/eigen3 -fomit-frame-pointer -ffast-math -fopenmp -I../include -c cpp_interface.cpp
icc: command line warning #10148: option '-march=x86-64' not supported
mkdir -p obj/
mv cpp_interface.o obj/cpp_interface.o
icc -o libuvlm.dylib obj/cpp_interface.o -I../include -shared -fPIC -fopenmp -L/Users/rmudafor/miniconda3/envs/sharpy_env/lib -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl
ipo: warning #11016: Warning unknown option --no-as-needed
ld: unknown option: --no-as-needed
make[1]: *** [Makefile:51: libuvlm.dylib] Error 1
make[1]: Leaving directory '/Users/rmudafor/Desktop/UVLM/src'
make: *** [Makefile:10: default] Error 2
cp: lib/*: No such file or directory
```

With clang or GNU (`g++-9`), I get this one:
```
(sharpy_env) >>mbp@~/Desktop/UVLM (develop *)$ ./run_make.sh 
mkdir -p lib
make -C src/
make[1]: Entering directory '/Users/rmudafor/Desktop/UVLM/src'
clang -fPIC -O3 -std=c++14 -march=x86-64 -mtune=generic -DEIGEN_USE_MKL_ALL -I/Users/rmudafor/miniconda3/envs/sharpy_env/include -I/Users/rmudafor/miniconda3/envs/sharpy_env/include/eigen3 -fomit-frame-pointer -ffast-math -fopenmp -I../include -c cpp_interface.cpp
clang: error: unsupported option '-fopenmp'
make[1]: *** [Makefile:54: cpp_interface.o] Error 1
make[1]: Leaving directory '/Users/rmudafor/Desktop/UVLM/src'
make: *** [Makefile:10: default] Error 2
cp: lib/*: No such file or directory
```

It looks like something isn't compiling successfully, but I don't see an indication of what the problem is.

**Comment by fonsocarre** [comment]
Hi @rafmudaf thanks for taking the time to review this.

The second problem is probably because of the lack of native OpenMP support for `clang`. Only removing the `-fopenmp` won't fix it, because there are some OMP function calls being made without wrapping in `#ifdef` blocks. I'll fix it tomorrow if I have time.

Concerning the first one, I cleaned the makefile in linux and (my fault) I assumed the interface would be the same on Mac. If you remove the `--no-as-needed` does it work?

If you really want to run it today, I'd suggest going for the docker, that I know that it works in MacOS. I'll try my best to have it fixed tomorrow.

**Comment by rafmudaf** [comment]
@fonsocarre Thanks for the quick response.

For what it's worth, I got the OpenMP error with the GNU compilers, as well. `gcc` can map to `clang` on Mac (not sure if there's a default `g++` that also maps to `clang`), but I made sure to use the full path when setting the CPP variable:
```
CPP = /usr/local/bin/g++-9
```

As for removing the `--no-as-needed` flag, it does get further but I think the flags are formulated for GNU rather than the Intel compiler so there are other problems. Here's the next error when I remove that flag and try to compile with `icc`:
```
(sharpy_env) >>mbp@~/Desktop/UVLM (develop *)$ ./run_make.sh 
mkdir -p lib
make -C src/
make[1]: Entering directory '/Users/rmudafor/Desktop/UVLM/src'
icc -fPIC -O3 -std=c++14 -march=x86-64 -mtune=generic -DEIGEN_USE_MKL_ALL -I/Users/rmudafor/miniconda3/envs/sharpy_env/include -I/Users/rmudafor/miniconda3/envs/sharpy_env/include/eigen3 -fomit-frame-pointer -ffast-math -fopenmp -I../include -c cpp_interface.cpp
icc: command line warning #10148: option '-march=x86-64' not supported
mkdir -p obj/
mv cpp_interface.o obj/cpp_interface.o
icc -o libuvlm.dylib obj/cpp_interface.o -I../include -shared -fPIC -fopenmp -L/Users/rmudafor/miniconda3/envs/sharpy_env/lib -Wl, -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl
ld: library not found for -lmkl_gnu_thread
make[1]: *** [Makefile:51: libuvlm.dylib] Error 1
make[1]: Leaving directory '/Users/rmudafor/Desktop/UVLM/src'
make: *** [Makefile:10: default] Error 2
cp: lib/*: No such file or directory
```

And no rush on my end, but this is part of the review for the JOSS paper so it may be more time-critical for you. @petebachant tested the docker usage so I wanted to make sure it would compile locally as documented.
