### ISSUE TITLE
Vortex radius square use in linear functions

### ISSUE THREAD

**Issue by ngoiz** [fonsocarre/UVLM#6]
The parameter `vortex_radius_sq` is calculated from the input for the `vortex_radius`. However, when the `vortex_radius` gets small, the square can lead to numerical issues.

In the linear functions it is used solely as a reference of up to where to compute (i.e. the actual value of the square of the `vortex_radius` is not required) thus `vortex_radius_sq` could be any number such that it doesn't cause these inaccuracies.

Using: 4a4a1fea2128d3231bccfb7a3ba90525c165b5ab

**Comment by ArturoMS13** [comment]
i have set "vortex_radius_sq = vortex_radius". We have found accuracy issues when "vortex_radius_sq = vortex_radius*vortex_radius".  We believe "vortex_radius_sq" is a limit for numerical accuracy so the changes makes sense.

**Comment by ngoiz** [comment]
Works, thanks!
